config/routes.rb
Pagos::Application.routes.draw do
  
  resources :tb_via 

  resources :mini_pagos

root :to => "home#index"  

end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :tb_via
  attr_accessible :direccion, :nro_direccion

  validates :direccion, :presence => true

  

end

app/models/mini_pago.rb
class MiniPago < ActiveRecord::Base
  attr_accessible :dni, :fecha_pago, :folio, :id_pago, :monto
end

app/models/tb_vium.rb
class TbVium < ActiveRecord::Base
  attr_accessible :descripcion, :fec_registro, :id_estado, :id_via


has_many :tb_via
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/direccion_controller.rb
class DireccionController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mini_pagos_controller.rb
class MiniPagosController < ApplicationController
  # GET /mini_pagos
  # GET /mini_pagos.json
  def index
    @mini_pagos = MiniPago.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mini_pagos }
    end
  end

  # GET /mini_pagos/1
  # GET /mini_pagos/1.json
  def show
    @mini_pago = MiniPago.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mini_pago }
    end
  end

  # GET /mini_pagos/new
  # GET /mini_pagos/new.json
  def new
    @mini_pago = MiniPago.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mini_pago }
    end
  end

  # GET /mini_pagos/1/edit
  def edit
    @mini_pago = MiniPago.find(params[:id])
  end

  # POST /mini_pagos
  # POST /mini_pagos.json
  def create
    @mini_pago = MiniPago.new(params[:mini_pago])

    respond_to do |format|
      if @mini_pago.save
        format.html { redirect_to @mini_pago, notice: 'Mini pago was successfully created.' }
        format.json { render json: @mini_pago, status: :created, location: @mini_pago }
      else
        format.html { render action: "new" }
        format.json { render json: @mini_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mini_pagos/1
  # PUT /mini_pagos/1.json
  def update
    @mini_pago = MiniPago.find(params[:id])

    respond_to do |format|
      if @mini_pago.update_attributes(params[:mini_pago])
        format.html { redirect_to @mini_pago, notice: 'Mini pago was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mini_pago.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mini_pagos/1
  # DELETE /mini_pagos/1.json
  def destroy
    @mini_pago = MiniPago.find(params[:id])
    @mini_pago.destroy

    respond_to do |format|
      format.html { redirect_to mini_pagos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tb_via_controller.rb
class TbViaController < ApplicationController
  # GET /tb_via
  # GET /tb_via.json
  def index
    @tb_via = TbVium.find(:all, :order => 'id_via')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tb_via }
    end
  end

  # GET /tb_via/1
  # GET /tb_via/1.json
  def show
    @tb_vium = TbVium.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tb_vium }
    end
  end

  # GET /tb_via/new
  # GET /tb_via/new.json
  def new
    @tb_vium = TbVium.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tb_vium }
    end
  end

  # GET /tb_via/1/edit
  def edit
    @tb_vium = TbVium.find(params[:id])
  end

  # POST /tb_via
  # POST /tb_via.json
  def create
    @tb_vium = TbVium.new(params[:tb_vium])

    respond_to do |format|
      if @tb_vium.save
        format.html { redirect_to @tb_vium, notice: 'Tb vium was successfully created.' }
        format.json { render json: @tb_vium, status: :created, location: @tb_vium }
      else
        format.html { render action: "new" }
        format.json { render json: @tb_vium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tb_via/1
  # PUT /tb_via/1.json
  def update
    @tb_vium = TbVium.find(params[:id])

    respond_to do |format|
      if @tb_vium.update_attributes(params[:tb_vium])
        format.html { redirect_to @tb_vium, notice: 'Tb vium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tb_vium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tb_via/1
  # DELETE /tb_via/1.json
  def destroy
    @tb_vium = TbVium.find(params[:id])
    @tb_vium.destroy

    respond_to do |format|
      format.html { redirect_to tb_via_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/direccion_helper.rb
module DireccionHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mini_pagos_helper.rb
module MiniPagosHelper
end

app/helpers/tb_via_helper.rb
module TbViaHelper
end

app/views/home/index.html.erb
<h1>Hello Recuperare!</h1>
<p>Buscame en app/views/home/index.html.erb</p>
<div>
  <h3>Manya</h3><br>
  <p>
  	Te dije que avanze las <%= link_to "Vias", tb_via_path %>
  </p>
</div>

<footer>
	<div>
		<h2>O puedes venir a nuestro :
			<a 
			href="http://192.168.2.6:8080/sinc-financiero/login.htm" 
				target="_blank">
		 	last project
			</a>
		</h2>
	</div>
	<div>
		<h3>
			O puedes revisar nuestros <%= link_to "mini_pagos", mini_pagos_path %>
		</h3>
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pagos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mini_pagos/_form.html.erb
<%= form_for(@mini_pago) do |f| %>
  <% if @mini_pago.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mini_pago.errors.count, "error") %> prohibited this mini_pago from being saved:</h2>

      <ul>
      <% @mini_pago.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_pago %><br />
    <%= f.text_field :id_pago %>
  </div>
  <div class="field">
    <%= f.label :dni %><br />
    <%= f.text_area :dni %>
  </div>
  <div class="field">
    <%= f.label :folio %><br />
    <%= f.text_area :folio %>
  </div>
  <div class="field">
    <%= f.label :monto %><br />
    <%= f.text_field :monto %>
  </div>
  <div class="field">
    <%= f.label :fecha_pago %><br />
    <%= f.date_select :fecha_pago %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mini_pagos/edit.html.erb
<h1>Editing mini_pago</h1>

<%= render 'form' %>

<%= link_to 'Show', @mini_pago %> |
<%= link_to 'Back', mini_pagos_path %>

app/views/mini_pagos/index.html.erb
<h1>Listing mini_pagos</h1>

<table>
  <tr>
    <th>Id pago</th>
    <th>Dni</th>
    <th>Folio</th>
    <th>Monto</th>
    <th>Fecha pago</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mini_pagos.each do |mini_pago| %>
  <tr>
    <td><%= mini_pago.id_pago %></td>
    <td><%= mini_pago.dni %></td>
    <td><%= mini_pago.folio %></td>
    <td><%= mini_pago.monto %></td>
    <td><%= mini_pago.fecha_pago %></td>
    <td><%= link_to 'Show', mini_pago %></td>
    <td><%= link_to 'Edit', edit_mini_pago_path(mini_pago) %></td>
    <td><%= link_to 'Destroy', mini_pago, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mini pago', new_mini_pago_path %>

app/views/mini_pagos/new.html.erb
<h1>New mini_pago</h1>

<%= render 'form' %>

<%= link_to 'Back', mini_pagos_path %>

app/views/mini_pagos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id pago:</b>
  <%= @mini_pago.id_pago %>
</p>

<p>
  <b>Dni:</b>
  <%= @mini_pago.dni %>
</p>

<p>
  <b>Folio:</b>
  <%= @mini_pago.folio %>
</p>

<p>
  <b>Monto:</b>
  <%= @mini_pago.monto %>
</p>

<p>
  <b>Fecha pago:</b>
  <%= @mini_pago.fecha_pago %>
</p>


<%= link_to 'Edit', edit_mini_pago_path(@mini_pago) %> |
<%= link_to 'Back', mini_pagos_path %>

app/views/tb_via/_form.html.erb
<%= form_for(@tb_vium) do |f| %>
  <% if @tb_vium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tb_vium.errors.count, "error") %> prohibited this tb_vium from being saved:</h2>

      <ul>
      <% @tb_vium.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_via %><br />
    <%= f.number_field :id_via %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :fec_registro %><br />
    <%= f.date_select :fec_registro %>
  </div>
  <div class="field">
    <%= f.label :id_estado %><br />
    <%= f.number_field :id_estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tb_via/edit.html.erb
<h1>Editing tb_vium</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @tb_vium %> |
<%= link_to 'Atras', tb_via_path %>

app/views/tb_via/index.html.erb
<h1>Listado de Vias</h1>
<link href="../../assets/css/bootstrap.css" rel="stylesheet">
<table class="table table-bordered">
  <tr>
    <th>Id via</th>
    <th>Descripcion</th>
    <th>Fec registro</th>
    <th>Id estado</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tb_via.each do |tb_vium| %>
  <tr>
    <td><%= tb_vium.id_via %></td>
    <td><%= tb_vium.descripcion %></td>
    <td><%= tb_vium.fec_registro %></td>
    <td><%= tb_vium.id_estado %></td>
    <td><%= link_to 'Mostrar', tb_vium %></td>
    <td><%= link_to 'Editar', edit_tb_vium_path(tb_vium) %></td>
    <td><%= link_to 'Eliminar', tb_vium, method: :delete, data: { confirm: 'Seguro?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Crear nuevo', new_tb_vium_path %>

app/views/tb_via/new.html.erb
<h1>New tb_vium</h1>

<%= render 'form' %>

<%= link_to 'Back', tb_via_path %>

app/views/tb_via/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id via:</b>
  <%= @tb_vium.id_via %>
</p>

<p>
  <b>Descripcion:</b>
  <%= @tb_vium.descripcion %>
</p>

<p>
  <b>Fec registro:</b>
  <%= @tb_vium.fec_registro %>
</p>

<p>
  <b>Id estado:</b>
  <%= @tb_vium.id_estado %>
</p>


<%= link_to 'Editar', edit_tb_vium_path(@tb_vium) %> |
<%= link_to 'Atras', tb_via_path %>